version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    env_file: .env
    environment:
      RAILS_ENV: development
  database:
    image: postgres:12.1
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
  redis:
    image: redis:5.0.7
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: 
      - app
      - database
      - redis
    env_file: .env
    environment:
      RAILS_ENV: development
    command: "rm -f tmp/pids/server/pid && bundle exec sidekiq"

volumes:
  db_data:
